apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-webapp
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: root-webpage
          servicePort: http
      - path: /nexus/?(.*)
        backend:
          serviceName: nexus-webapp
          servicePort: webapp
      - path: /nexus-spark/?(.*)
        backend:
          serviceName: nexus-webapp-spark
          servicePort: webapp