# Duplicate this file and put your customization here

storageClass: hostpath

rootWebpage:
  enabled: true

webapp:
  distributed:
    image: nexusjpl/nexus-webapp:distributed.0.1.3
    driver:
      # Refer to the configuration options available at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
    executor:
      # Refer to the configuration options available at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md
      cores: 1
      instances: 2
      memory: "512m"

ingester:
  dataHostPath: /Users/edford/Desktop/ingestion_test
  dataMountPath: /data
  collection:
  granule:
    image: nexusjpl/ningester2:latest


cassandra:
  replicas: 2
  storage: 13Gi
  requests:
    cpu: 1
    memory: 3Gi
  limits:
    cpu: 1
    memory: 3Gi

solr:
  replicas: 2
  storage: 10Gi
  heap: 4g
  requests:
    memory: 5Gi
    cpu: 1 
  limits:
    memory: 5Gi
    cpu: 1

zookeeper:
  replicas: 3 
  memory: 1Gi
  cpu: 0.5
  storage: 8Gi

ingressEnabled: false

onEarthProxyIP: ""

##
## Configuration values for the nginx-ingress dependency.
## ref: https://github.com/helm/charts/tree/master/stable/nginx-ingress
nginx-ingress:
  controller:
    scope:
      enabled: true
    kind: DaemonSet
    service:
      enabled: true
      type: LoadBalancer
  defaultBackend:
    enabled: false

rabbitmq:
  username: guest
  password: guest